function Hd = noiseCompensation(fs)

%% Filter builder
% [0, 30, 1000, 2000, 5000, 7500, 10000, 12000, 15000, 16000, 17000, 18000, 20000, 22050]
% [0.5, 1, 1, 0.95, 0.75, 0.6, 0.4, 0.3, 0.25, 0.25, 0.25, 0.3, 0.5, 1]
% 0.05 ripple
% Arbitrary responce

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 26-May-2017 15:35:34

Rp = 0.05;   % Ripple Value

% Frequency Vector
F  = [0 0.0014 0.045 0.09 0.227 0.340 0.454 0.544 0.680 0.726 0.771 0.816 ...
    0.907 1] * (fs/2);

% Amplitude Vector
A  = [0.5 1 1 0.95 0.75 0.6 0.4 0.3 0.25 0.25 0.25 0.3 0.5 1];

h = fdesign.arbmag('F,A,R', F, A, Rp, fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any');

% viewer = fvtool(Hd);
% viewer.Fs = 48000;
% viewer.FrequencyScale = 'Log';

end